[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s,%(msecs)03d [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_file_level = INFO
log_date_format = %Y-%m-%d %H:%M:%S
addopts = -v -s --html=reports/report.html --self-contained-html -p no:warnings --alluredir=reports
pythonpath=.
env_files=.env